spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/validator?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  # xml扫描路径
  mapperLocations: classpath:mapper/*Mapper.xml
  typeEnumsPackage: com.zukxu.validator.entity

server:
  port: 31001
  servlet:
    context-path: /val
